name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  push:
    # run when the workflow file is modified
    branches:
      - main
    paths:
      - ".github/workflows/youtube-cards.yml"
  # run when dispatched from actions tab
  workflow_dispatch:

permissions:
  contents: write  # This gives the workflow permission to push commits
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          playlist_id: PLpm-6wQM9fecWDubnKkOcJYP20lL8fP0C
          comment_tag_name: YOUTUBE-CARDS
          max_title_lines: 2
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          output_type: html
